### ISSUE TITLE
Support for Augmented and Diminished Triads?

### ISSUE THREAD

**Issue by connorheyz** [yuma-m/pychord#41]
I stumbled upon your repo while looking for a way to easily parse my database of chord progressions into midi files. However, my database has a lot of augmented and diminished triads in the progressions. The program was not able to recognize augmented or diminished chords, which slightly disappointed me. It would be nice to have these triads built-in instead of needing a custom parser to recognize them

Regards, 
Connor

**Comment by yuma-m** [comment]
Hi @connorheyz,

Thank you for your feedback.

>  The program was not able to recognize augmented or diminished chords

Could you explain the chord which could not be handled?

**Comment by philipmat** [comment]
I've run into some issues with some diminished and augmented + note chords, even though `note_to_chord` recognizes it:

- diminished 7th, for example Ddim7 or Dº7 https://www.basicmusictheory.com/d-diminished-7th-chord
``python
>>> note_to_chord(["D", "F", "Ab", "Cb"]) # D diminished seventh
Ddim7
>>> Chord("Ddim7")  
ValueError: Unknown quality: dim7
>>> Chord("Dº7") 
ValueError: Unknown quality: º7
>>>Chord("Ddim")
['D', 'F', 'G#']
```

- augumented 6th
```python
>>>Chord("Daug")
['D', 'F#', 'A#']
>>> Chord("Daug6")
ValueError: Unknown quality: aug6
```

**Comment by yuma-m** [comment]
Hi @philipmat, thank you for your feedback.
Yes, the current `dim6` should be called `dim7`. I will fix this.

Regarding missing qualities, could you consider handling them by using `QualityManager`?

```python
from pychord import Chord, QualityManager
quality_manager = QualityManager()
quality_manager.set_quality("7add11", (0, 4, 7, 10, 17))
print(Chord("Bb7add11").components())
# ['Bb', 'D', 'F', 'Ab', 'Eb']
```

**Comment by philipmat** [comment]
Thank you.

Now that I've seen in your PR what all needs to be changed, would you accept a further PR that increases the list of qualities with some of the more extended stuff like "m9#5" , etc? (including tests and everything, of course)

**Comment by yuma-m** [comment]
@philipmat Yes, I welcome contributions. If there're many qualities you want to add, it would be great to separate them into some different pull requests.
