### ISSUE TITLE
Chords with time to generate a midi file

### ISSUE THREAD

**Issue by SutirthaChakraborty** [yuma-m/pychord#50]
Hi, 

I have a code that extracts the chords from the audio. It returns the following 
1. Start time of the chord 
2.  Signature
3. Name of the chord
(Image attached)
![image](https://user-images.githubusercontent.com/47362033/103403172-47099800-4b75-11eb-84d8-6a9867a38f4b.png)

I want to recreate a MIDI file based on that information. How can I do that?

Thanks, 
Suti

**Comment by yuma-m** [comment]
Hi, there are some libraries to create a MIDI file. You can integrate PyChord with those libraries by using `Chord.components_with_pitch` method.
https://github.com/vishnubob/python-midi
https://github.com/craffel/pretty-midi

**Comment by yuma-m** [comment]
Please confirm the example: https://github.com/yuma-m/pychord/blob/master/examples/pychord-midi.py
