### ISSUE TITLE
2 notes chords. Probably "sus" chord is impemented in a wrong way

### ISSUE THREAD

**Issue by koto-wheel** [yuma-m/pychord#53]
Hello,

# Description

I'm using pychord-0.5.1

In constant QUALITY_DICT, there are 2 "2 chords qualities"
* **5**: (0, 7)
* **sus**: (0,7)

# Suggestion

* I think that **sus** quality should be implemented with value **(0,5)** since I guess it corresponds to the interval between degree-V to degree-VIII (from G to upper C for example)

* If I'm right, could you please make the change ?

Sincerely,
Serge.

**Comment by yuma-m** [comment]
Hi @koto-wheel, thank you for using PyChord.

As I'm not an expert on music theory, but according to the following pages, sus means sus4. In that case, sus should be (0, 5, 7) instead of (0, 7).

Do you have any references to indicate sus should be (0, 5)?

http://musictheory.pugetsound.edu/mt21c/SimpleSusChords.html
> The two basic sus chords are the sus4 and sus2 chords. In the sus4 chord (also labeled simply as “sus”), a perfect 4th replaces the 3rd of the chord.

https://www.talkbass.com/threads/what-is-the-difference-between-sus-sus2-sus4-chords-and-other-questions.359845/#post-4607380
> sus chords, by definition, have no third. They are called sus because the middle note of the chord is "suspended", with the implication that it will "resolve" back to the third.

> As I understand it, "sus" by itself implies sus4 (in my own music I always specify sus2 or sus4 to avoid confusion).

**Comment by koto-wheel** [comment]
Hello,if you're not expert on music theory I can tell you that I know things about music theory. So I agree with what you wrote. For me, sus and sus4 mean tthe same thing and correspond to (0,5,7).  I have never read things about 2 notes chords but you have related to that in the QUALITY_DICT constant.So, I agree with the fact sus = sus4 = (0,5,7). Which means you should change QUALITY_ADDICT constant. I will also have more suggestions about other entries in this constant. I wrote then on github. If you don't know enough on music theory, I think I know enough about music theory to add some changes.Can you let me suggest you some changes on a branch of your project please to make it easier to show you all I have in mind ?Serge.envoyé : 17 février 2021 à 14:15de : Yuma Mihira <notifications@github.com>à : yuma-m/pychord <pychord@noreply.github.com>cc : koto-wheel <serge.robinson@orange.fr>, Mention <mention@noreply.github.com>objet : Re: [yuma-m/pychord] 2 notes chords. Probably "sus" chord is impemented in a wrong way (#53) Hi @koto-wheel, thank you for using PyChord.As I'm not an expert on music theory, but according to the following pages, sus means sus4. In that case, sus should be (0, 5, 7) instead of (0, 7).Do you have any references to indicate sus should be (0, 5)?http://musictheory.pugetsound.edu/mt21c/SimpleSusChords.htmlThe two basic sus chords are the sus4 and sus2 chords. In the sus4 chord (also labeled simply as “sus”), a perfect 4th replaces the 3rd of the chord.https://www.talkbass.com/threads/what-is-the-difference-between-sus-sus2-sus4-chords-and-other-questions.359845/#post-4607380sus chords, by definition, have no third. They are called sus because the middle note of the chord is "suspended", with the implication that it will "resolve" back to the third.As I understand it, "sus" by itself implies sus4 (in my own music I always specify sus2 or sus4 to avoid confusion).—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yuma-m** [comment]
Hi,

Actually, I have learned the very basics of harmony and I compose songs as a hobby. I'm familiar with the chords used in pop songs but don't understand the classical theory well.

Yes, I noticed another issue you created, let me confirm it later. Your contribution to PyChord is welcome. Please feel free to create a pull-request and let us discuss on it.

As for sus chord, I will create a pull request to fix this.

**Comment by koto-wheel** [comment]
Hello,

I created a fork of pychord and made some changes. A created a branch from **bugfix/sus**. I merged my changes on my fork **master** branch. Should I make a pull request on your **bugfix/sus** branch ? Changes I added also concern issue #54

 

Serge.

**Comment by koto-wheel** [comment]
I've just made a pull request on branch **bugfix/sus**.
