### ISSUE TITLE
Could be included omitt chords and diminished 5th triad.

### ISSUE THREAD

**Issue by pedropolidoro** [yuma-m/pychord#69]
Could be included in qualities.py the diminished 5th triad
and chords with omitted notes using either 'no' or 'omitt

2 notes
	('no5', (0, 4)), # ('omitt5', (0, 4))
	('m(no5)', (0, 3)), # ('m(omitt5)', (0, 3))

3 notes
	('(b5)', (0, 4, 6)),

4 notes
	('sus4add2', (0, 2, 5, 7),
	('sus4add9', (0, 5, 7, 14),

**Comment by yuma-m** [comment]
Hi @pedropolidoro, thank you for raising this.
Is "omitt" typo of "omit"?

**Comment by pedropolidoro** [comment]
> 
> 
> Hi @pedropolidoro, thank you for raising this. Is "omitt" typo of "omit"?

Yes, it is omit. I confused the orthography because it's in English, sorry.
